name: CI-CodeBuild

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: codebuild-ubuntu-small
    strategy:
      matrix:
        node:
          - 20
    steps:
      - name: ‚¨áÔ∏è Checkout
        uses: actions/checkout@v2

      - name: ‚éî Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: üì• Download deps
        run: npm ci

      - name: üß™ Run lint
        run: npm run lint

  build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node:
          - 16
          - 18
          - 20
        os: [codebuild-ubuntu-small]
        browser:
          - FirefoxHeadless
        include:
          - os: windows-latest
            node: 20
            browser: FirefoxHeadless

    steps:

      - name: ‚¨áÔ∏è Checkout
        uses: actions/checkout@v2

      - name: ‚éî Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: üì• Download deps
        run: npm ci

      - name: Run coverage
        run: npm test

      - name: Run browser tests
        if: matrix.node == 20
        run: npm run mocha-browser-test -- --browsers ${{ matrix.browser }}  --timeout 10000
        env:
          DISPLAY: :99.0

      - name: Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == '20'
        run: npm run coverage && npx nyc report --reporter=lcov

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.node == '20'
        uses: coverallsapp/github-action@1.1.3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
